fragment LayoutQueryFragment on Query {
  getGlobalDocument(relativePath: "index.json") {
    data {
      header {
        posts {
          href
          label
        }
        nav {
          href
          label
        }
      }
      footer {
        social {
          facebook
          twitter
          instagram
          github
        }
      }
      theme {
        darkMode
      }
    }
  }
}
