fragment PostsParts on Posts {
  title
  heroImg
  excerpt
  author {
    ... on Document {
      id
    }
  }
  date
  _body
}

fragment GlobalParts on Global {
  extra {
    __typename
    verse {
      __typename
      body
      author
    }
    email
    donate
  }
  header {
    __typename
    posts {
      __typename
      href
      label
    }
    nav {
      __typename
      href
      label
    }
  }
  footer {
    __typename
    social {
      __typename
      facebook
      twitter
      instagram
      pinterest
      gmail
      github
    }
  }
  theme {
    __typename
    darkMode
  }
}

fragment AuthorsParts on Authors {
  name
  avatar
}

fragment PagesParts on Pages {
  blocks {
    __typename
    ... on PagesBlocksSocial {
      title
      description
      socialImg
    }
    ... on PagesBlocksVerseblock {
      null
    }
    ... on PagesBlocksContent {
      body
      color
    }
  }
}
